dist: xenial
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"
branches:
  only:
  - master
  - development
  - "/^[vV]?\\d+\\.\\d+\\.\\d+$/"
before_install: unset _JAVA_OPTIONS
install:
- "$HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh"
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then echo "$VAADIN_CHARTS_LICENSE_CODE"
  > ~/.vaadin.charts.developer.license; fi;
script: mvn --quiet --activate-profiles !development-build,!release-build --settings
  .travis.settings.xml clean cobertura:cobertura package
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true
after_deploy:
- echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc
  && conda activate qbic-docs-build
- mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml
  site
- ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages"
  "This commit was performed from travis-ci.com using a personal access key" "Build
  ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this
  build found at $TRAVIS_JOB_WEB_URL"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
    rooms:
    - secure: "***"
env:
  global:
  - secure: QFrMHG1lh3DE69YgLblEZEPfTAevTWUj+X0Takqdar9TKfCu3B9MD7saO1lvmuwcuHeYH55UbWwDqtoiHe9it93BUQWXN5BZkjz7dk8ad+0cZBSDfTlHIw6JuA9la7NGPEANliPnehSNCpIXh8+yMl8tsW9mqnEQv8A/ffDjM0LXUZ0oebDk1DUgvcpdNneZkjsTL+iMut4J/diGm9hYD9nEno94+U4JVDi18WroXT2g1qV498wJkexhvGxyxilPI52WZ14dkJktND4R2e8LabBwY/DVYpsW99W7S15nnlE5w22VWedjcQETSVoIza0Lu7vDi/N2v2qSo5pGi1Tdtje+WkkUiqItV6N+rpa61qFEZK2LLwzN+nTVPD2xISPsrNfzBShSpZOiC5B2I5qQHkruY4t9Ca1CkkizTYckkKmID1ey8yY7RaF0RPMCPrzCcqtSDg/p1pQkJV3Xo4CW4DBAwDpuSfOdGDB4FIg9F4X4q5sFWyeLkjZYZzW2ItL8bSqypKaKb9sn53umvBdpsFXDBtT70IQRcE68xY7QImXX8G0yDhd4+WNhe6oYM0sWM4Qt8fibSRQ1sJmJiJiUkHjrrZB17lQqc7FeSo/EH4p4ny8VMwvPlHSnGMgZSQkiexnZuvBChdCyZBoYku3uii4qmzATlx/mRDvDH0Ocq1s=
  - secure: jJB1JyMnxE/fqPTV70EFRq46cpr7uyAchy0JYAtmtPM9BM0m+JV07Hq+NaMd+nl8EeQOiW+SONlfI5rYjfnSsLXlnFQqViMSFwQjEilcodOFNVWxXB5bKvcHMf8qbVjMs8bcZk5/dIh02KTWitqPOU4rW/5w/0lNpZgw5o2y5EMFGUGkObLad3G3dfWtAlthLZMyPI4n9X8jn4+/reZ3kNzN9NnBt8rcSmbZTTNUWQYHloxaczxdW5QJRL6qigd5gLJ/I5ebswclE4oaDrVlcuJrMaRNoJaZ8ucf1NoZ7l3cz4tkvntEYBz7Mctp2Ddk4jVEdecdJfvWIQ0wwNKmKM2UEyLXuXlJiYhovmN6DZznbMgPEUJNvkppxf55Phzch2Mj+fkZYoXQZlj0bQUsPfuwRPYpROd1ONXkF8JaUGVKc9/X1D4JPpWL6a6iswzWFqTQcI15Ub2ghdkp1dTGE6yd5sQfEM84d9QhP1LCp0AgDDI5rcB70pOUHNjbMTN+7gOM+gWOj5M2HYW3WLgINoUBHRUY5PHZkH/EvSCv8F1ho9RDBdDRdNCgpwdCyINfBLeInk7EUA6cGrL2NZ7ob/ynXwUDoVCrM73P2OOBSBfRsTGuqe7p1dymkiENlZP51nB1he8oxzSOs0czo9HG+s35AhOl+W83Q/UtjRFi88E=
  - secure: cRvSsUvuo1dtb1OBgUnd54GW96PD0pBZ397XlTWGG9Ql5ZjRtKsq31I8wscDo4+Njigpd3s2SSMpvQ92h8GKon9hhqtql9TT2ugZvFGlzeR7yBnOWoMiOgmnQ8ZcWeIxjyMjK+71sbVEXNmaU/tGVlfnwtrK9HEpEEqHVnT5KZWLELXoKaIZwtCsB8o35ZY/H+Qq8lG+DRoHinyo6WrrW6p4VT+b2AY3hDBLqqusUDhNxeSni+13dJ+bCoGk+FaGAcZNhEiGRfsYq5B32eDCBQ49MWHl3PmZ3Mvkfp7Zm2iNDSNVS8vs51W6AdiY43karSHKiiDuMTREL2LEJm50XugrcB/I6+ypwhDVSbwokkIgnhIO1LQQhCQcac4nt9NBfX4RnsdfnPxVndtLzeOGxW2Kmwg/HULf2qvJSbFo1b+p7wJf9tu+V4rDF156v4rI6EJf3qb/D7eBjuzmvyWl8AozO8XVjqepPaS6iFVjkpLYAy9zGkSZfkc3SJTcrUSq5wGfvqr0e+bkHakXSwn0PK3y+aGOuzA4nezwGgbfqumzOBao1IdSIe+qM5Ug2ew87WWQ6oZb2aV7z0icS0ROXc65mhE3W6Hl+kATTepdMVo2rqCMlLulY1EABFglfb1oEn4UG+KgDVhBjf0Cva8foUSROuSIG4lgM4aZu5e2Fgk=
  - secure: 2xbjoObhoBjjYkmKtBHih2zdBC7OtCsZGPoODQi0EACb6icOmSplxGfD1KXRKipsVn1l7SORewfZb7itPYw9iRzT/+5wPSmhWw3c8ZHehZTJO2KDbsTXmy2QtZyb0JUmtoqvzJBipTxXo1xNqm7Jd6vVDOKGYbhwQnaum/18hasJfiPEM+mO4RYnax0AVbUYjt70ElrhSCn9UAn+BTYgjBrBL9wS1m+LtYSefEzP+6nWWgUUzktgR5KLYiFkCwYuZgoEjaGGuWVruuvljkIp/Ah6PBTyMwWFDkOShM/IufLLzk7hf2BYxu7nH+Wc2EWZLeSkl4TSLqbYrkUxIiinpX/JBJJzgJEN8aPQJ8/206sf45mRgmfoQrBHFN+BktFOnbmCTG3W7nRhahBTvrWGsmdhg/OOTSqxWecmnzgpkcmxxeQjeA4IzMVPLeGETIF9pQlq/Z+g5FEjqHloUjda6n6A8jhFaAgxutjOhLAt8b3C75OomlpgPGeiWKyMdKqiC5WB3Lh9IK+lcvyVlvKMzZ0O2ofGmMxZ/lrYUzingM3vAa1C4zlUk+xR5zaw0VI08A41sCPI9J+EF0ZbSbpXt6O4yanvshRC/jnxerdhMUgT2ZH4wJ8GVsLz2NimjBhGJ3xrVjaSwYkBXILp4bUPtsA2HzXzCEtXbW5LvZz4fns=
